services:
  ms-configs:
    image: sarapura12/ms-configserver
    container_name: ms-configs
    mem_limit: 800m
    expose:
      - "8085"
    ports:
      - "8085:8085"
    networks:
        - team-network
  
  eurekaserver:
    image: sarapura12/eurekaserver:latest
    mem_limit: 800m
    ports:
      - "8761:8761"
    networks:
        - team-network
    depends_on:
      - ms-configs
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: dev
      SPRING_CONFIG_IMPORT: optional:configserver:http://ms-configs:8085/

  ms-sales:
    image: sarapura12/ms-sales:latest
    container_name: ms-sales
    mem_limit: 800m
    expose:
      - "8080"
    ports:
      - "8080:8080"
    deploy:
        restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
            
    environment:
        SPRING_PROFILE_ACTIVE: dev
        SPRING_CONFIG_IMPORT: optional:configserver:http://ms-configs:8085/
    networks:
      - team-network
    depends_on:
      - ms-configs
      - msDB
  

  ms-products:
    image: sarapura12/ms-products:latest
    container_name: ms-products
    mem_limit: 800m
    expose:
      - "8081"
    ports:
      - "8081:8081"
    deploy:
        restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
    environment:
        SPRING_PROFILE_ACTIVE: dev
        SPRING_CONFIG_IMPORT: optional:configserver:http://ms-configs:8085/
    networks:
      - team-network
    depends_on:
      - ms-configs
      - msDB

  ms-clients:
    image: sarapura12/ms-clients:latest
    container_name: ms-clients
    mem_limit: 800m
    expose:
      - "8082"
    ports:
      - "8082:8082"
    deploy:
        restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
    environment:
        SPRING_PROFILE_ACTIVE: dev
        SPRING_CONFIG_IMPORT: optional:configserver:http://ms-configs:8085/
    networks:
      - team-network
    depends_on:
      - ms-configs
      - msDB


  msDB:
    image: mysql:latest
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: msDB
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 2s
      retries: 10
      timeout: 10s
    restart: always
    networks:
      - team-network

networks:
  team-network:
    driver: bridge