services:

  ms-sales:
    image: sarapura12/ms-sales:latest
    container_name: ms-sales
    mem_limit: 800m
    ports:
      - "8080:8080"
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://msDB:3306/mssalesDB?createDatabaseIfNotExist=true&autoReconnect=true&serverTimeZone=GMT-3
      JDBC_DATABASE_USERNAME: root
      JDBC_DATABASE_PASSWORD: admin
    networks:
      - sarapura12-network
    depends_on:
      - msDB

  ms-products:
    image: sarapura12/ms-products:latest
    container_name: ms-products
    mem_limit: 800m
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://msDB:3306/msproductsDB?createDatabaseIfNotExist=true&autoReconnect=true&serverTimeZone=GMT-3
      JDBC_DATABASE_USERNAME: root
      JDBC_DATABASE_PASSWORD: admin
    ports:
      - "8081:8081"
    networks:
      - sarapura12-network
    depends_on:
      - msDB

  ms-clients:
    image: sarapura12/ms-clients:latest
    container_name: ms-clients
    mem_limit: 800m
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://msDB:3306/msclientsDB?createDatabaseIfNotExist=true&autoReconnect=true&serverTimeZone=GMT-3
      JDBC_DATABASE_USERNAME: root
      JDBC_DATABASE_PASSWORD: admin
    ports:
      - "8082:8082"
    networks:
      - sarapura12-network
    depends_on:
      - msDB


  msDB:
    image: mysql:latest
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: msDB
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 2s
      retries: 10
      timeout: 10s
    restart: always
    networks:
      - sarapura12-network

networks:
  sarapura12-network:
    driver: bridge