version: '3.7'

services:
  api_service:
    build: application
    container_name: ms-products
    ports:
      - "8080:8080"
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://msproductsDB:3306/productsDB?createDatabaseIfNotExist=true&autoReconnect=true&serverTimeZone=GMT-3
      JDBC_DATABASE_USERNAME: root
      JDBC_DATABASE_PASSWORD: admin
    restart: always
    networks:
        - my_app
    depends_on:
     - msproductsDB

  msproductsDB:
    image: mysql:latest
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: productsDB
    networks:
        - my_app
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 2s
      retries: 10
      timeout: 10s
    restart: always

networks:
  my_app:
    driver: bridge